on:
  pull_request:

name: "Build PHP Docker Images"

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build-and-push-docker:
    name: "Build PHP Docker Images"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
        php-target:
          - "cli"
          - "fpm"
          - "zts"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Install Docker Composer 2.x"
        run: |
          curl -fL https://raw.githubusercontent.com/docker/compose-switch/master/install_on_linux.sh | sudo sh
          sudo  update-alternatives --display docker-compose
          docker -v
          docker-compose -v

      - name: "Build ${{ matrix.php-target }} ${{ matrix.php-version }}"
        working-directory: php
        env:
          PHP_VERSION: ${{ matrix.php-version }}
          PHP_TARGET: ${{ matrix.php-target }}
          DOCKER_REGISTRY: "prooph/docker-files/"
        run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
